[package]
name = "tahm-kench-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
curl = "0.4.46"
serde = { version = "1.0.204", features = ["derive"] }
serde_derive = "1.0.210"
serde_json = "1.0.128"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["rt", "rt-multi-thread", "macros"] }
toml = "0.8.19"
glob = "0.3.1"
ethers = { version = "2.0", features = ["abigen", "async-std"] }
dotenv = "0.15.0"