[package]
name = "tahm-kench-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
bytes = "1.7.2"
clap = { version = "4.5.13", features = ["derive"] }
config = "0.14.0"
curl = "0.4.46"
dotenv = "0.15.0"
ethers = { tag = "v2.0.15-fix-reconnections", features = [
  "ws",
  "rustls",
], git = "https://github.com/yetanotherco/ethers-rs.git" }
glob = "0.3.1"
hex = "0.4.3"
rpassword = "7.3.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_derive = "1.0.210"
serde_json = "1.0.128"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["rt", "rt-multi-thread", "macros"] }
toml = "0.8.19"
