contract_address = "0xe9aad76249b425bff2eeef8d284ae6b772d657b7"
token_address = "0xA64F13F05479C8d1eB5adF6cDB85fA2303CcFC0f"
[chain]
etherscan_api_key = "2G4MBDIY1RNFHVZS27HR1KKVBHCX8YJ7WE"
rpc_url = "https://ethereum-holesky-rpc.publicnode.com"
