[package]
name = "aligned-sp1-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
rsa = "0.9.6"
hex = "0.4.3"
sp1-zkvm = "3.0.0"
serde = "1.0.210"
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2", features = ["keccak"] }
serde_json = "1.0.128"

[dev-dependencies]
sp1-sdk = "3.0.0"
