[package]
name = "ecies"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
hex = { workspace = true}
tiny-keccak = { workspace = true }

[dev-dependencies]
sp1-derive = "3.0.0"